services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  social:
    build: .
    image: raghavajag/social-ts
    environment:
      - PORT=5000
    depends_on:
      - mongo
      - redis
    env_file:
      - .env

  mongo:
    build: ./mongodb_rs
    restart: always
    env_file:
      - mongo.env
    ports:
      - "27017:27017"

  redis:
    image: redis
